// pin configuration
#define BR2U_ESC_1_PIN 23
#define BR2U_ESC_2_PIN 22
#define BR2U_HEAD_SERVO_PIN 14
#define BR2U_LEFT_HAND_SERVO_PIN 27
#define BR2U_RIGHT_HAND_SERVO_PIN 26
#define BR2U_CAN_DOOR_SERVO_PIN 19
#define BR2U_LEFT_CAN_SERVO_PIN 18
#define BR2U_RIGHT_CAN_SERVO_PIN 15
#define BR2U_RANDOM_SEED_PIN 36

// ESC configuration
#define BR2U_MIN_ESC_MICROSECONDS 1100
#define BR2U_CENTER_ESC_MICROSECONDS 1500
#define BR2U_MAX_ESC_MICROSECONDS 1900
#define BR2U_ESC_1_REVERSE false
#define BR2U_ESC_2_REVERSE true

// Hand servo config
#define BR2U_LEFT_HAND_SERVO_CENTER_ANGLE 90
#define BR2U_RIGHT_HAND_SERVO_CENTER_ANGLE 90
#define BR2U_LEFT_HAND_SERVO_ANGLE_LIMIT 55
#define BR2U_RIGHT_HAND_SERVO_ANGLE_LIMIT 55