#define FERRY_RACER_THROTTLE_ESC_PIN 32
#define FERRY_RACER_STEERING_SERVO_PIN 33
#define FERRY_RACER_HEAD_SERVO_PIN 25
#define FERRY_RACER_LEFT_LED_PIN 26
#define FERRY_RACER_RIGHT_LED_PIN 27
#define FERRY_RACER_RANDOM_SEED_PIN 36

#define FERRY_RACER_MIN_ESC_MICROSECONDS 1300
#define FERRY_RACER_CENTER_ESC_MICROSECONDS 1500
#define FERRY_RACER_MAX_ESC_MICROSECONDS 1700
#define FERRY_RACER_ESC_REVERSE false

#define FERRY_RACER_SERVO_ZERO_ANGLE 90
#define FERRY_RACER_SERVO_ANGLE_LIMIT 30
#define FERRY_RACER_SERVO_REVERSE false
