// pin configuration
#define MINI_SENTRY_LEFT_DOOR_SERVO_PIN 21
#define MINI_SENTRY_RIGHT_DOOR_SERVO_PIN 19

#define MINI_SENTRY_ESC_1_PIN 32
#define MINI_SENTRY_ESC_2_PIN 23
#define MINI_SENTRY_ESC_3_PIN 22

#define MINI_SENTRY_LED_1_PIN 33
#define MINI_SENTRY_LED_2_PIN 25
#define MINI_SENTRY_LED_3_PIN 26
#define MINI_SENTRY_LED_4_PIN 27
#define MINI_SENTRY_LED_5_PIN 14
#define MINI_SENTRY_LEFT_DOOR_LED_PIN 18
#define MINI_SENTRY_RIGHT_DOOR_LED_PIN 5

#define MINI_SENTRY_RANDOM_SEED_PIN 36


// ESC configuration
#define MINI_SENTRY_MIN_ESC_MICROSECONDS 1100
#define MINI_SENTRY_CENTER_ESC_MICROSECONDS 1500
#define MINI_SENTRY_MAX_ESC_MICROSECONDS 1900
#define MINI_SENTRY_ESC_1_REVERSE true
#define MINI_SENTRY_ESC_2_REVERSE true
#define MINI_SENTRY_ESC_3_REVERSE true

// servo configuration
#define MINI_SENTRY_LEFT_DOOR_ZERO_ANGLE 70
#define MINI_SENTRY_RIGHT_DOOR_ZERO_ANGLE 93