// pin configuration
#define MINI_SENTRY_LEFT_DOOR_SERVO_PIN 32
#define MINI_SENTRY_RIGHT_DOOR_SERVO_PIN 21
#define MINI_SENTRY_ESC_1_PIN 27
#define MINI_SENTRY_ESC_2_PIN 25
#define MINI_SENTRY_ESC_3_PIN 22


// ESC configuration
#define MINI_SENTRY_MIN_ESC_MICROSECONDS 1100
#define MINI_SENTRY_CENTER_ESC_MICROSECONDS 1500
#define MINI_SENTRY_MAX_ESC_MICROSECONDS 1900
#define MINI_SENTRY_THROTTLE_ESC_REVERSE true
#define MINI_SENTRY_STEERING_ESC_REVERSE true

// servo configuration
#define MINI_SENTRY_LEFT_DOOR_ZERO_ANGLE 70
#define MINI_SENTRY_RIGHT_DOOR_ZERO_ANGLE 110