// droid config
// #define ESC_DRIVE
// #define MX1508_DRIVE
#define NEO_PIXEL_LED
// #define REGULAR_LED


// pin configuration
#define MINI_R2D2_ESC_1_PIN 26
#define MINI_R2D2_ESC_2_PIN 25
#define MINI_R2D2_HEAD_SERVO_PIN 15
#define MINI_R2D2_LEFT_ARM_SERVO_PIN 19
#define MINI_R2D2_RIGHT_ARM_SERVO_PIN 18
#define MINI_R2D2_SHOULDER_SERVO_PIN 27
#define MINI_R2D2_CENTER_LIFT_SERVO_PIN 14
#define MINI_R2D2_RANDOM_SEED_PIN 36
#define MINI_R2D2_NEOPIXEL_PIN 23

// ESC configuration
#define MINI_R2D2_MIN_ESC_MICROSECONDS 1100
#define MINI_R2D2_CENTER_ESC_MICROSECONDS 1500
#define MINI_R2D2_MAX_ESC_MICROSECONDS 1900
#define MINI_R2D2_ESC_1_REVERSE false
#define MINI_R2D2_ESC_2_REVERSE true

// ARM servo config
#define MINI_R2D2_LEFT_ARM_SERVO_CENTER_ANGLE 93
#define MINI_R2D2_RIGHT_ARM_SERVO_CENTER_ANGLE 93
#define MINI_R2D2_LEFT_ARM_SERVO_ANGLE_LIMIT 70
#define MINI_R2D2_RIGHT_ARM_SERVO_ANGLE_LIMIT 70

// 2-3-2 servo config
#define MINI_R2D2_SHOULDER_SERVO_CENTER_ANGLE 45
#define MINI_R2D2_CENTER_LIFT_SERVO_CENTER_ANGLE 90

// holoprojector config
#define MINI_R2D2_HOLOPROJECTOR_CENTER_PVM 320
#define MINI_R2D2_HOLOPROJECTOR_MIN_PVM 275
#define MINI_R2D2_HOLOPROJECTOR_MAX_PVM 375

// periscope config
#define MINI_R2D2_PERISCOPE_DOWN_PVM 460
#define MINI_R2D2_PERISCOPE_UP_PVM 240