#define MINI_MOUSE_ESC_PIN 23
#define MINI_MOUSE_SERVO_PIN 19

#define MINI_MOUSE_MIN_ESC_MICROSECONDS 1100
#define MINI_MOUSE_CENTER_ESC_MICROSECONDS 1500
#define MINI_MOUSE_MAX_ESC_MICROSECONDS 1900
#define MINI_MOUSE_ESC_REVERSE true

#define MINI_MOUSE_SERVO_ZERO_ANGLE 90
#define MINI_MOUSE_SERVO_ANGLE_LIMIT 45
#define MINI_MOUSE_SERVO_REVERSE true
